- name: Check if Wireguard interface exists already
  ansible.builtin.stat:
    path: "/sys/class/net/{{ wireguard.interface_name }}"
  register: wg_iface_check

- name: Stop Wireguard
  ansible.builtin.shell:
    cmd: "/usr/bin/env wg-quick down {{ wireguard.interface_name }}"
  register: stop
  when: wg_iface_check.stat.exists
- debug:
    msg: "{{ stop.stdout_lines | join('\n') }}"

- name: Start Wireguard
  ansible.builtin.shell:
    cmd: "/usr/bin/env wg-quick up /etc/wireguard/{{ wireguard.interface_name }}.conf"
  register: start
- debug:
    msg: "{{ start.stdout_lines | join('\n') }}"
