- name: Check if Wireguard interface exists already
  ansible.builtin.stat:
    path: "/sys/class/net/{{ wireguard_interface_name }}"
  register: wg_iface_check

- name: Stop Wireguard
  ansible.builtin.shell:
    cmd: "wg-quick down {{ wireguard_interface_name }} 2>&1"
  register: wg_down
  when: wg_iface_check.stat.exists
- ansible.builtin.debug:
    msg: "{{ wg_down.stdout_lines | join('\n') }}"
  when: wg_down is defined and wg_down.stdout_lines is defined

- name: Start Wireguard
  ansible.builtin.shell:
    cmd: "wg-quick up /etc/wireguard/{{ wireguard_interface_name }}.conf 2>&1"
  register: wg_up
- ansible.builtin.debug:
    msg: "{{ wg_up.stdout_lines | join('\n') }}"
