---
- name: Restart Wireguard
  ansible.builtin.include_tasks: restart-wireguard.yml

- name: Reload UFW
  community.general.ufw:
    state: reloaded

- name: Restart UFW
  block:
    - community.general.ufw:
        state: disabled
    - community.general.ufw:
        state: enabled
